# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from meshpipe.v1 import data_pb2 as meshpipe_dot_v1_dot_data__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in meshpipe/v1/data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MeshpipeDataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDashboardStats = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/GetDashboardStats',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.DashboardRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.DashboardResponse.FromString,
                _registered_method=True)
        self.ListPackets = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/ListPackets',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.ListPacketsRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.ListPacketsResponse.FromString,
                _registered_method=True)
        self.StreamPackets = channel.unary_stream(
                '/meshpipe.v1.MeshpipeData/StreamPackets',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.ListPacketsRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.Packet.FromString,
                _registered_method=True)
        self.ListNodes = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/ListNodes',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.ListNodesRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.ListNodesResponse.FromString,
                _registered_method=True)
        self.GetNode = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/GetNode',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.GetNodeRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.GetNodeResponse.FromString,
                _registered_method=True)
        self.GetGatewayStats = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/GetGatewayStats',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.GatewayFilter.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.GatewayStatsResponse.FromString,
                _registered_method=True)
        self.ListLinks = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/ListLinks',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.ListLinksRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.ListLinksResponse.FromString,
                _registered_method=True)
        self.ListTraceroutes = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/ListTraceroutes',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.ListTraceroutesRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.ListTraceroutesResponse.FromString,
                _registered_method=True)
        self.ListRangeTests = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/ListRangeTests',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.ListRangeTestsRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.ListRangeTestsResponse.FromString,
                _registered_method=True)
        self.ListStoreForward = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/ListStoreForward',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.ListStoreForwardRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.ListStoreForwardResponse.FromString,
                _registered_method=True)
        self.ListPaxcounter = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/ListPaxcounter',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.ListPaxcounterRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.ListPaxcounterResponse.FromString,
                _registered_method=True)
        self.ListNodeLocations = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/ListNodeLocations',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.ListNodeLocationsRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.ListNodeLocationsResponse.FromString,
                _registered_method=True)
        self.GetChatWindow = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/GetChatWindow',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.GetChatWindowRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.GetChatWindowResponse.FromString,
                _registered_method=True)
        self.GetNodeAnalytics = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/GetNodeAnalytics',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.GetNodeAnalyticsRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.GetNodeAnalyticsResponse.FromString,
                _registered_method=True)
        self.GetGatewayOverview = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/GetGatewayOverview',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.GetGatewayOverviewRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.GetGatewayOverviewResponse.FromString,
                _registered_method=True)
        self.GetAnalyticsSummary = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/GetAnalyticsSummary',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.GetAnalyticsSummaryRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.GetAnalyticsSummaryResponse.FromString,
                _registered_method=True)
        self.ListTraceroutePackets = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/ListTraceroutePackets',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.ListTraceroutePacketsRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.ListTraceroutePacketsResponse.FromString,
                _registered_method=True)
        self.GetTracerouteDetails = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/GetTracerouteDetails',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.GetTracerouteDetailsRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.GetTracerouteDetailsResponse.FromString,
                _registered_method=True)
        self.ListTracerouteHops = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/ListTracerouteHops',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.ListTracerouteHopsRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.ListTracerouteHopsResponse.FromString,
                _registered_method=True)
        self.GetTracerouteGraph = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/GetTracerouteGraph',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.TracerouteGraphRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.TracerouteGraphResponse.FromString,
                _registered_method=True)
        self.ListNodeDirectReceptions = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/ListNodeDirectReceptions',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.ListNodeDirectReceptionsRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.ListNodeDirectReceptionsResponse.FromString,
                _registered_method=True)
        self.ListNodeNames = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/ListNodeNames',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.ListNodeNamesRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.ListNodeNamesResponse.FromString,
                _registered_method=True)
        self.ListPrimaryChannels = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/ListPrimaryChannels',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.ListPrimaryChannelsRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.ListPrimaryChannelsResponse.FromString,
                _registered_method=True)
        self.Healthz = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/Healthz',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/meshpipe.v1.MeshpipeData/GetVersion',
                request_serializer=meshpipe_dot_v1_dot_data__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=meshpipe_dot_v1_dot_data__pb2.VersionResponse.FromString,
                _registered_method=True)


class MeshpipeDataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDashboardStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPackets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPackets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGatewayStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLinks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTraceroutes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRangeTests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStoreForward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPaxcounter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodeLocations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeAnalytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGatewayOverview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnalyticsSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTraceroutePackets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTracerouteDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTracerouteHops(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTracerouteGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodeDirectReceptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodeNames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPrimaryChannels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Healthz(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeshpipeDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDashboardStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDashboardStats,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.DashboardRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.DashboardResponse.SerializeToString,
            ),
            'ListPackets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPackets,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.ListPacketsRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.ListPacketsResponse.SerializeToString,
            ),
            'StreamPackets': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPackets,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.ListPacketsRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.Packet.SerializeToString,
            ),
            'ListNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodes,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.ListNodesRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.ListNodesResponse.SerializeToString,
            ),
            'GetNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNode,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.GetNodeRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.GetNodeResponse.SerializeToString,
            ),
            'GetGatewayStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGatewayStats,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.GatewayFilter.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.GatewayStatsResponse.SerializeToString,
            ),
            'ListLinks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLinks,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.ListLinksRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.ListLinksResponse.SerializeToString,
            ),
            'ListTraceroutes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTraceroutes,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.ListTraceroutesRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.ListTraceroutesResponse.SerializeToString,
            ),
            'ListRangeTests': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRangeTests,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.ListRangeTestsRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.ListRangeTestsResponse.SerializeToString,
            ),
            'ListStoreForward': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStoreForward,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.ListStoreForwardRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.ListStoreForwardResponse.SerializeToString,
            ),
            'ListPaxcounter': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPaxcounter,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.ListPaxcounterRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.ListPaxcounterResponse.SerializeToString,
            ),
            'ListNodeLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodeLocations,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.ListNodeLocationsRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.ListNodeLocationsResponse.SerializeToString,
            ),
            'GetChatWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatWindow,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.GetChatWindowRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.GetChatWindowResponse.SerializeToString,
            ),
            'GetNodeAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeAnalytics,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.GetNodeAnalyticsRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.GetNodeAnalyticsResponse.SerializeToString,
            ),
            'GetGatewayOverview': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGatewayOverview,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.GetGatewayOverviewRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.GetGatewayOverviewResponse.SerializeToString,
            ),
            'GetAnalyticsSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalyticsSummary,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.GetAnalyticsSummaryRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.GetAnalyticsSummaryResponse.SerializeToString,
            ),
            'ListTraceroutePackets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTraceroutePackets,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.ListTraceroutePacketsRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.ListTraceroutePacketsResponse.SerializeToString,
            ),
            'GetTracerouteDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTracerouteDetails,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.GetTracerouteDetailsRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.GetTracerouteDetailsResponse.SerializeToString,
            ),
            'ListTracerouteHops': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTracerouteHops,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.ListTracerouteHopsRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.ListTracerouteHopsResponse.SerializeToString,
            ),
            'GetTracerouteGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTracerouteGraph,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.TracerouteGraphRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.TracerouteGraphResponse.SerializeToString,
            ),
            'ListNodeDirectReceptions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodeDirectReceptions,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.ListNodeDirectReceptionsRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.ListNodeDirectReceptionsResponse.SerializeToString,
            ),
            'ListNodeNames': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodeNames,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.ListNodeNamesRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.ListNodeNamesResponse.SerializeToString,
            ),
            'ListPrimaryChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPrimaryChannels,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.ListPrimaryChannelsRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.ListPrimaryChannelsResponse.SerializeToString,
            ),
            'Healthz': grpc.unary_unary_rpc_method_handler(
                    servicer.Healthz,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.HealthCheckRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=meshpipe_dot_v1_dot_data__pb2.GetVersionRequest.FromString,
                    response_serializer=meshpipe_dot_v1_dot_data__pb2.VersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meshpipe.v1.MeshpipeData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meshpipe.v1.MeshpipeData', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeshpipeData(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDashboardStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/GetDashboardStats',
            meshpipe_dot_v1_dot_data__pb2.DashboardRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.DashboardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPackets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/ListPackets',
            meshpipe_dot_v1_dot_data__pb2.ListPacketsRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.ListPacketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPackets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/StreamPackets',
            meshpipe_dot_v1_dot_data__pb2.ListPacketsRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.Packet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/ListNodes',
            meshpipe_dot_v1_dot_data__pb2.ListNodesRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.ListNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/GetNode',
            meshpipe_dot_v1_dot_data__pb2.GetNodeRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.GetNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGatewayStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/GetGatewayStats',
            meshpipe_dot_v1_dot_data__pb2.GatewayFilter.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.GatewayStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/ListLinks',
            meshpipe_dot_v1_dot_data__pb2.ListLinksRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.ListLinksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTraceroutes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/ListTraceroutes',
            meshpipe_dot_v1_dot_data__pb2.ListTraceroutesRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.ListTraceroutesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRangeTests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/ListRangeTests',
            meshpipe_dot_v1_dot_data__pb2.ListRangeTestsRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.ListRangeTestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStoreForward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/ListStoreForward',
            meshpipe_dot_v1_dot_data__pb2.ListStoreForwardRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.ListStoreForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPaxcounter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/ListPaxcounter',
            meshpipe_dot_v1_dot_data__pb2.ListPaxcounterRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.ListPaxcounterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodeLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/ListNodeLocations',
            meshpipe_dot_v1_dot_data__pb2.ListNodeLocationsRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.ListNodeLocationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/GetChatWindow',
            meshpipe_dot_v1_dot_data__pb2.GetChatWindowRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.GetChatWindowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/GetNodeAnalytics',
            meshpipe_dot_v1_dot_data__pb2.GetNodeAnalyticsRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.GetNodeAnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGatewayOverview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/GetGatewayOverview',
            meshpipe_dot_v1_dot_data__pb2.GetGatewayOverviewRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.GetGatewayOverviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnalyticsSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/GetAnalyticsSummary',
            meshpipe_dot_v1_dot_data__pb2.GetAnalyticsSummaryRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.GetAnalyticsSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTraceroutePackets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/ListTraceroutePackets',
            meshpipe_dot_v1_dot_data__pb2.ListTraceroutePacketsRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.ListTraceroutePacketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTracerouteDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/GetTracerouteDetails',
            meshpipe_dot_v1_dot_data__pb2.GetTracerouteDetailsRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.GetTracerouteDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTracerouteHops(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/ListTracerouteHops',
            meshpipe_dot_v1_dot_data__pb2.ListTracerouteHopsRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.ListTracerouteHopsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTracerouteGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/GetTracerouteGraph',
            meshpipe_dot_v1_dot_data__pb2.TracerouteGraphRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.TracerouteGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodeDirectReceptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/ListNodeDirectReceptions',
            meshpipe_dot_v1_dot_data__pb2.ListNodeDirectReceptionsRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.ListNodeDirectReceptionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodeNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/ListNodeNames',
            meshpipe_dot_v1_dot_data__pb2.ListNodeNamesRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.ListNodeNamesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPrimaryChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/ListPrimaryChannels',
            meshpipe_dot_v1_dot_data__pb2.ListPrimaryChannelsRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.ListPrimaryChannelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Healthz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/Healthz',
            meshpipe_dot_v1_dot_data__pb2.HealthCheckRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshpipe.v1.MeshpipeData/GetVersion',
            meshpipe_dot_v1_dot_data__pb2.GetVersionRequest.SerializeToString,
            meshpipe_dot_v1_dot_data__pb2.VersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
